/// Flutter icons RtlhIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RtlhIcon
///      fonts:
///       - asset: fonts/RtlhIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class RtlhIcon {
  RtlhIcon._();

  static const _kFontFam = 'RtlhIcon';
  static const _kFontPkg = null;

  static const IconData logo_rtlh = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
