name: rtlh_app
description: RTLH application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  awesome_dialog: ^1.2.1
  bubble_bottom_bar: ^1.2.0
  carousel_slider: ^2.2.1
  crypto: ^2.1.5
  cupertino_icons: ^0.1.3
  device_preview: ^0.2.3
  division: ^0.8.8
  double_back_to_close_app: ^1.2.0
  email_validator: ^1.0.5
  expandable: ^4.1.4
  flushbar: ^1.10.4
  flutter_inappwebview: ^4.0.0+4
  flutter_slidable: ^0.5.7
  flutter_speed_dial: ^1.2.5
  flutter_spinkit: ^4.1.2
  flutter_staggered_grid_view: ^0.3.2
  geolocator: ^6.1.13
  get: ^3.10.2
  get_ip: ^0.4.0
  get_version: ^0.2.2
  google_fonts: ^1.1.0
  google_maps_flutter: ^0.5.33
  http: ^0.12.2
  intl: ^0.16.1
  modal_bottom_sheet: ^0.2.2
  outline_material_icons: ^0.1.1
  path_provider: ^1.6.18
  permission_handler: ^5.0.1+1
  pull_to_refresh: ^1.6.3
  shared_preferences: ^0.5.10
  shimmer: ^1.1.2
  slider_button: ^0.6.0
  splashscreen: ^1.2.0
  sqflite: ^1.3.1+1
  supercharged: ^1.10.0
  toast: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/fonts/
    - assets/logo/
    - assets/img/
    - assets/img/icon/
    - assets/img/flag/
    - assets/img/background/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito.ttf
    - family: RtlhIcon
      fonts:
        - asset: assets/fonts/RtlhIcon.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
